# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'backgroundselector.ui'
#
# Created: Tue Oct 20 21:46:02 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_BackgroundSelector(object):
    def setupUi(self, BackgroundSelector):
        BackgroundSelector.setObjectName("BackgroundSelector")
        BackgroundSelector.resize(497, 446)
        BackgroundSelector.setMaximumSize(QtCore.QSize(800, 600))
        self.vboxlayout = QtGui.QVBoxLayout(BackgroundSelector)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.backgroundNameList = QtGui.QListWidget(BackgroundSelector)
        self.backgroundNameList.setMinimumSize(QtCore.QSize(120, 0))
        self.backgroundNameList.setObjectName("backgroundNameList")
        self.hboxlayout.addWidget(self.backgroundNameList)
        self.groupBox_2 = QtGui.QGroupBox(BackgroundSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.backgroundPreview = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backgroundPreview.sizePolicy().hasHeightForWidth())
        self.backgroundPreview.setSizePolicy(sizePolicy)
        self.backgroundPreview.setMinimumSize(QtCore.QSize(200, 160))
        self.backgroundPreview.setFrameShape(QtGui.QFrame.Box)
        self.backgroundPreview.setObjectName("backgroundPreview")
        self.vboxlayout1.addWidget(self.backgroundPreview)
        self.hboxlayout.addWidget(self.groupBox_2)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.groupBox = QtGui.QGroupBox(BackgroundSelector)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.labelAuthor = QtGui.QLabel(self.groupBox)
        self.labelAuthor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAuthor.setObjectName("labelAuthor")
        self.vboxlayout2.addWidget(self.labelAuthor)
        self.labelContact = QtGui.QLabel(self.groupBox)
        self.labelContact.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelContact.setObjectName("labelContact")
        self.vboxlayout2.addWidget(self.labelContact)
        self.labelDescription = QtGui.QLabel(self.groupBox)
        self.labelDescription.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDescription.setObjectName("labelDescription")
        self.vboxlayout2.addWidget(self.labelDescription)
        self.hboxlayout1.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.backgroundAuthor = QtGui.QLabel(self.groupBox)
        self.backgroundAuthor.setObjectName("backgroundAuthor")
        self.vboxlayout3.addWidget(self.backgroundAuthor)
        self.backgroundContact = QtGui.QLabel(self.groupBox)
        self.backgroundContact.setObjectName("backgroundContact")
        self.vboxlayout3.addWidget(self.backgroundContact)
        self.backgroundDescription = QtGui.QLabel(self.groupBox)
        self.backgroundDescription.setObjectName("backgroundDescription")
        self.vboxlayout3.addWidget(self.backgroundDescription)
        self.hboxlayout1.addLayout(self.vboxlayout3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.vboxlayout.addWidget(self.groupBox)
        self.kcfg_backgroundName = QtGui.QLineEdit(BackgroundSelector)
        self.kcfg_backgroundName.setEnabled(False)
        self.kcfg_backgroundName.setFrame(False)
        self.kcfg_backgroundName.setReadOnly(False)
        self.kcfg_backgroundName.setObjectName("kcfg_backgroundName")
        self.vboxlayout.addWidget(self.kcfg_backgroundName)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)

        self.retranslateUi(BackgroundSelector)
        QtCore.QMetaObject.connectSlotsByName(BackgroundSelector)

    def retranslateUi(self, BackgroundSelector):
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BackgroundSelector", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BackgroundSelector", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAuthor.setText(QtGui.QApplication.translate("BackgroundSelector", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelContact.setText(QtGui.QApplication.translate("BackgroundSelector", "Contact:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDescription.setText(QtGui.QApplication.translate("BackgroundSelector", "Description:", None, QtGui.QApplication.UnicodeUTF8))

