# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tilesetselector.ui'
#
# Created: Tue Oct 20 21:46:02 2009
#      by: PyQt4 UI code generator 4.5.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_TilesetSelector(object):
    def setupUi(self, TilesetSelector):
        TilesetSelector.setObjectName("TilesetSelector")
        TilesetSelector.resize(497, 446)
        TilesetSelector.setMaximumSize(QtCore.QSize(800, 600))
        self.vboxlayout = QtGui.QVBoxLayout(TilesetSelector)
        self.vboxlayout.setSpacing(6)
        self.vboxlayout.setMargin(9)
        self.vboxlayout.setObjectName("vboxlayout")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setMargin(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.tilesetNameList = QtGui.QListWidget(TilesetSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilesetNameList.sizePolicy().hasHeightForWidth())
        self.tilesetNameList.setSizePolicy(sizePolicy)
        self.tilesetNameList.setMinimumSize(QtCore.QSize(120, 0))
        self.tilesetNameList.setObjectName("tilesetNameList")
        self.hboxlayout.addWidget(self.tilesetNameList)
        self.groupBox_2 = QtGui.QGroupBox(TilesetSelector)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.vboxlayout1 = QtGui.QVBoxLayout(self.groupBox_2)
        self.vboxlayout1.setSpacing(6)
        self.vboxlayout1.setMargin(9)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.tilesetPreview = QtGui.QWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tilesetPreview.sizePolicy().hasHeightForWidth())
        self.tilesetPreview.setSizePolicy(sizePolicy)
        self.tilesetPreview.setMinimumSize(QtCore.QSize(120, 160))
        self.tilesetPreview.setObjectName("tilesetPreview")
        self.vboxlayout1.addWidget(self.tilesetPreview)
        self.hboxlayout.addWidget(self.groupBox_2)
        self.vboxlayout.addLayout(self.hboxlayout)
        self.groupBox = QtGui.QGroupBox(TilesetSelector)
        self.groupBox.setObjectName("groupBox")
        self.hboxlayout1 = QtGui.QHBoxLayout(self.groupBox)
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setMargin(9)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.vboxlayout2 = QtGui.QVBoxLayout()
        self.vboxlayout2.setSpacing(6)
        self.vboxlayout2.setMargin(0)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.labelAuthor = QtGui.QLabel(self.groupBox)
        self.labelAuthor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelAuthor.setObjectName("labelAuthor")
        self.vboxlayout2.addWidget(self.labelAuthor)
        self.labelContact = QtGui.QLabel(self.groupBox)
        self.labelContact.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelContact.setObjectName("labelContact")
        self.vboxlayout2.addWidget(self.labelContact)
        self.labelDescription = QtGui.QLabel(self.groupBox)
        self.labelDescription.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDescription.setObjectName("labelDescription")
        self.vboxlayout2.addWidget(self.labelDescription)
        self.hboxlayout1.addLayout(self.vboxlayout2)
        self.vboxlayout3 = QtGui.QVBoxLayout()
        self.vboxlayout3.setSpacing(6)
        self.vboxlayout3.setMargin(0)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.tilesetAuthor = QtGui.QLabel(self.groupBox)
        self.tilesetAuthor.setObjectName("tilesetAuthor")
        self.vboxlayout3.addWidget(self.tilesetAuthor)
        self.tilesetContact = QtGui.QLabel(self.groupBox)
        self.tilesetContact.setObjectName("tilesetContact")
        self.vboxlayout3.addWidget(self.tilesetContact)
        self.tilesetDescription = QtGui.QLabel(self.groupBox)
        self.tilesetDescription.setObjectName("tilesetDescription")
        self.vboxlayout3.addWidget(self.tilesetDescription)
        self.hboxlayout1.addLayout(self.vboxlayout3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout1.addItem(spacerItem)
        self.vboxlayout.addWidget(self.groupBox)
        self.kcfg_tilesetName = QtGui.QLineEdit(TilesetSelector)
        self.kcfg_tilesetName.setEnabled(False)
        self.kcfg_tilesetName.setFrame(False)
        self.kcfg_tilesetName.setReadOnly(False)
        self.kcfg_tilesetName.setObjectName("kcfg_tilesetName")
        self.vboxlayout.addWidget(self.kcfg_tilesetName)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.vboxlayout.addItem(spacerItem1)

        self.retranslateUi(TilesetSelector)
        QtCore.QMetaObject.connectSlotsByName(TilesetSelector)

    def retranslateUi(self, TilesetSelector):
        self.groupBox_2.setTitle(QtGui.QApplication.translate("TilesetSelector", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("TilesetSelector", "Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.labelAuthor.setText(QtGui.QApplication.translate("TilesetSelector", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelContact.setText(QtGui.QApplication.translate("TilesetSelector", "Contact:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDescription.setText(QtGui.QApplication.translate("TilesetSelector", "Description:", None, QtGui.QApplication.UnicodeUTF8))

