# SPDX-FileCopyrightText: 2024-2025 Scarlett Moore <sgmoore@kde.org>
#
# SPDX-License-Identifier: CC0-1.0
---
name: kajongg
confinement: strict
grade: stable
base: core24
adopt-info: kajongg
apps:
  kajongg:
    extensions:
      - kde-neon-6
    common-id: org.kde.kajongg
    desktop: usr/share/applications/org.kde.kajongg.desktop
    command: usr/bin/kajongg
    plugs:
      - audio-record
    environment:
      PYTHONUSERBASE: "$SNAP_USER_COMMON/.local"
      PYTHONPATH: "$PYTHONUSERBASE/lib/python3.12/site-packages:$SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/share/kajongg"
slots:
  session-dbus-interface:
    interface: dbus
    name: org.kde.kajongg
    bus: session
parts:
  python-deps:
    source: .
    plugin: python
    build-packages:
      - python3-dev
      - python3
    python-packages:
      - pyside6
      - qtpy
    build-environment:
      - PYTHONPATH: $CRAFT_STAGE/lib/python3.12/site-packages:$CRAFT_STAGE/usr/lib/python3/dist-packages
      - QT_API: pyside6
    override-build: |
      pip install --upgrade pip setuptools
      craftctl default
    prime:
      - -usr/bin/activate
      - -usr/bin/activate.csh
      - -usr/bin/activate.fish
      - -usr/bin/Activate.ps1
      - -usr/bin/python
      - -usr/bin/python3
      - -usr/bin/python3.12
      - -usr/bin/pip
      - -usr/bin/pip3
      - -usr/bin/pip3.10
      - -usr/bin/wheel
      - -usr/lib/python3.12/dist-packages/pip*
      - -usr/lib/python3.12/dist-packages/pkg_resources
      - -usr/lib/python3.12/dist-packages/setuptools*
      - -pyvenv.cfg
      - -lib
      - -lib64
      - -include
      - -share
    organize:
      bin: usr/bin
      lib/python3.12/site-packages: usr/lib/python3/dist-packages
  libkmahjongg:
    after:
      - python-deps
    plugin: cmake
    source: https://invent.kde.org/games/libkmahjongg.git
    stage-packages:
      - rsync
      - libpopt0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    override-stage: |
        craftctl default
        rsync -a --ignore-existing $CRAFT_PART_INSTALL/ /
  kajongg:
    after:
      - libkmahjongg
    parse-info:
      - usr/share/metainfo/org.kde.kajongg.appdata.xml
    plugin: cmake
    source: .
    source-type: local
    build-packages:
      - python3-twisted
      - libxkbcommon-dev
    stage-packages:
      - libxkbcommon0
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DQT_MAJOR_VERSION=6
      - -DBUILD_TESTING=OFF
    build-environment: &build-environment
      - LD_LIBRARY_PATH: >
          "/snap/mesa-2404/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/kde-qt6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libproxy:$LD_LIBRARY_PATH"
    prime:
      - -usr/lib/*/cmake/*
      - -usr/include/*
      - -usr/share/ECM/*
      - -usr/share/man/*
      - -usr/bin/X11
      - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET_BUILD_FOR/6.0.0
      - -usr/lib/aspell/*
      - -usr/share/lintian
    override-build: |
        craftctl default
        rm $CRAFT_PART_INSTALL/usr/bin/kajongg
        cp $CRAFT_PART_INSTALL/usr/share/kajongg/kajongg.py $CRAFT_PART_INSTALL/usr/bin/kajongg
        rm $CRAFT_PART_INSTALL/usr/bin/kajonggserver
        cp $CRAFT_PART_INSTALL/usr/share/kajongg/kajonggserver.py $CRAFT_PART_INSTALL/usr/bin/kajonggserver
  gpu-2404:
    after: [kajongg]
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
  cleanup:
    after:
      - kajongg
    plugin: nil
    build-snaps:
      - core24
      - kf6-core24
    override-prime: |
      set -eux
      for snap in "core24" "kf6-core24"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -rf "${CRAFT_PRIME}/{}" \;
      done
