[[tool.mypy.overrides]]
module = [
    "qtpy.*",
    "sip",
    "cx_Freeze",
    "PySide2",
    "kdepaths.*",
    "appversion",
    "zope.interface",
    "PyQt6.*",
    "twisted.*"]
ignore_missing_imports = true
